### ISSUE TITLE
plate number GM compatibility

### ISSUE THREAD

**Issue by nomisum** [gruppe-adler/grad-advancedLockpicking#1]
GM handles plates differently than vanilla (insignia, not obtainable by `setplatenumber`)

![20190610054008_1](https://user-images.githubusercontent.com/500164/59171251-692a6800-8b42-11e9-8dbc-82a4808fa72d.jpg)

**Comment by nomisum** [comment]
https://community.bistudio.com/wiki/Global_Mobilization_Insignia_(Vehicles)

will update if i get a response regarding setter fnc from GM

**Comment by nomisum** [comment]
`[vehicle player,"B-GM-1337",0,1] spawn gm_core_vehicles_fnc_vehicleMarkingsUpdateAttributes;`

https://feedback.bistudio.com/T140639

**Comment by McDiod** [comment]
Can be closed I guess?

**Comment by nomisum** [comment]
yes ,not tested but should work
